name: resume_classification
channels:
  - defaults
dependencies:
  - python=3.8
  - matplotlib
  - pandas
  - numpy
  - seaborn
  - tensorflow
  - scikit-learn
  - scikit-images
  - joblib
  - keras
  - google-colab
  - pillow
  - jupyter

